name: covid_info
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.3.0
  flutter_launcher_icons: ^0.7.5
  cupertino_icons: ^0.1.3
  sembast: ^2.4.4
  path_provider: ^1.6.8
  charts_flutter: ^0.9.0
  url_launcher: ^5.4.10
  font_awesome_flutter: ^8.8.1
  http: ^0.12.1
  intl: ^0.16.1
  geolocator: ^5.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
